### ISSUE TITLE
No CMD ["/bin/bash"] in dockerfile

### ISSUE THREAD

**Issue by Karmakstylez** [tgagor/docker-centos#1]
Can you add to the Entrypoint of your dockerfile the following: 

`CMD ["/bin/bash"]`

Because that will make your docker centos images interactive without having them force to use the docker run -dit bash command instead.

**Comment by tgagor** [comment]
Hi @Karmakstylez 

As explained in https://github.com/tgagor/docker-centos/pull/2
It's fixed right now.

Thanks again for reporting the issue.

**Comment by Karmakstylez** [comment]
Is it me or is it still not in the Dockerfile themselves? I do see them in the other Dockerfile you mentioned in #2 . But because you have other Dockerfiles yourself you also need to add the CMD in your own Dockerfile as well. That I was mentioning. Now everytime you build the Docker Container and run it you need to do --entrypoint /bin/bash, because your dockerfile does not have any CMD included.

Your CENTOS Dockerfile:
![image](https://user-images.githubusercontent.com/29887990/142079440-d40f78b1-3641-474e-835e-2e7483996726.png)

THE OTHER CENTOS IMAGE YOU MENTIONED:
![image](https://user-images.githubusercontent.com/29887990/142079630-dc38ab0f-4442-41e6-874f-b639b4be9853.png)

ALSO THE NEW RELEASE: 
![image](https://user-images.githubusercontent.com/29887990/142079916-82a970ab-c016-482f-9027-fb0ce68132fb.png)

OFFICIAL CENTOS RELEASE:
![image](https://user-images.githubusercontent.com/29887990/142080028-b72958ec-d6d3-4de2-87e8-fe6456f0e944.png)

Let me know if it properly fixed the issue?

**Comment by tgagor** [comment]
Exactly, it's not done in Dockerfile. It's another magic :)

**Comment by tgagor** [comment]
Actual fix happen here: https://github.com/tgagor/docker-centos/commit/e9638e520c9175fdf6e55f24ca0578b6b82ca408
