### ISSUE TITLE
systemctl does not work with Docker Image

### ISSUE THREAD

**Issue by Karmakstylez** [tgagor/docker-centos#4]
When I try to implement systemctl to enable services at bootup of the container I get the error: 
```
sh-4.4# systemctl
Failed to connect to bus: No such file or directory
```

I used the code from here: https://davescripts.com/docker-container-with-centos-8-apache-php-using-systemd

Could it be implemented?

**Comment by tgagor** [comment]
Hi @Karmakstylez 

Thank you for your report, but I don't see how your issue might be related to my images.
They are (more or less) just standard CentOS base images. I guess, that if the blog instructions don't work with mine images, they won't work with official one.

Sorry, but I don't plan to implement any special systemd handling. I can only suggest contacting with blog author.

Good luck!
